# 00 Fundamental Notes

In [4]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

1.13.1+rocm5.2


## Intro to tensors
### Creating a tensor

Base data structure in pytorch are tensors using `torch.Tensor()`

In [5]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([5,6])
vector

tensor([5, 6])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRTIX
MATRIX = torch.tensor([[4,3],
[9,10]])
MATRIX

tensor([[ 4,  3],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
tensor_practice = torch.Tensor([[[2,3,2]]])

In [21]:
tensor_practice.ndim

3

In [22]:
tensor_practice.shape

torch.Size([1, 1, 3])

lower case for scalar and vector

upper case for matrix and tensor

### Random Tensors

Making random tensors to simulate real data samples

In [26]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4532, 0.3525, 0.1159, 0.2721],
        [0.2483, 0.3095, 0.8153, 0.6857],
        [0.4178, 0.7750, 0.5616, 0.2140]])

In [27]:
random_tensor.ndim

2

In [29]:
# Creating a rng tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(244,244,3)) # height, width, color channels (RGB)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [31]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
torch.float32

torch.float32

### Create a range of tensors and tensors-like

In [38]:
# Use torch.range()
evens = torch.arange(start=0,end=10,step=2)

In [39]:
# tensors like
zero_likes = torch.zeros_like(input=evens)
zero_likes

tensor([0, 0, 0, 0, 0])