# 00 Fundamental Notes

In [6]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.2.0+rocm5.7


## Intro to tensors
### Creating a tensor

Base data structure in pytorch are tensors using `torch.Tensor()`

In [7]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# get tensor back as python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([5,6])
vector

tensor([5, 6])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRTIX
MATRIX = torch.tensor([[4,3],
[9,10]])
MATRIX

tensor([[ 4,  3],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
tensor_practice = torch.Tensor([[[2,3,2]]])

In [21]:
tensor_practice.ndim

3

In [22]:
tensor_practice.shape

torch.Size([1, 1, 3])

lower case for scalar and vector

upper case for matrix and tensor

### Random Tensors

Making random tensors to simulate real data samples

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[4.8999e-01, 6.9600e-04, 3.1661e-01, 9.3278e-01],
        [2.3280e-01, 7.8811e-01, 3.7628e-03, 2.1679e-01],
        [5.2329e-01, 8.6809e-02, 3.8480e-01, 7.7170e-01]])

In [24]:
random_tensor.ndim

2

In [25]:
# Creating a rng tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(244,244,3)) # height, width, color channels (RGB)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
torch.float32

torch.float32

### Create a range of tensors and tensors-like

In [29]:
# Use torch.range()
evens = torch.arange(start=0,end=10,step=2)

In [30]:
# tensors like
zero_likes = torch.zeros_like(input=evens)
zero_likes

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor dtypes is one of the 3 big erros in pytorch and deep learning
1. Tensors not right dytpe
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=None, #dtype?
                                device=None, # on cpu or gpu
                                requires_grad=False) # tracking gradients
float_32_tensor, float_32_tensor.dtype                            

(tensor([3., 6., 9.]), torch.float32)

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting info from tensors (Tensor Attributes)

* dtype - `tensor.dtype`
* shape - `tensor.shape`
* device - `tensor.device`

In [33]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6465, 0.6198, 0.4639, 0.9305],
        [0.3068, 0.4406, 0.4061, 0.9017],
        [0.4906, 0.8207, 0.3803, 0.6695]])

In [34]:
# details of some_tensor
print(some_tensor)
print(f"Dtype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.6465, 0.6198, 0.4639, 0.9305],
        [0.3068, 0.4406, 0.4061, 0.9017],
        [0.4906, 0.8207, 0.3803, 0.6695]])
Dtype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor opperations
* Add
* Sub
* Multiply element wise
* Divide
* Matrix multiply


In [35]:
tensor = torch.tensor ([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
# pytorch in-built func
torch.mul(tensor,10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix muliplication

2 ways to multiply matrices
1. element wise
2. dot product

In [40]:
# element wise
tensor * tensor

tensor([1, 4, 9])

In [41]:
%%time
# matrix mult
torch.matmul(tensor, tensor)

CPU times: user 375 µs, sys: 228 µs, total: 603 µs
Wall time: 328 µs


tensor(14)

### one of the most common errors in deep learning: shape errors
inner values of matrix (m x n) must be the same 

* `(m,n) @ (n,m)` works
* `(n,m) @ (n,m)` won't work

In [42]:
# shapes for matrix multi
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.mm(tensor_A, tensor_B.T) # torch.mm is an alias for torch.matmul                        

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [43]:
# tranpose to fix shape
tensor_B.T.shape

torch.Size([2, 3])

### Finding min, max, mean, sum etc (tensor aggregation)

In [44]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.min(x), x.max()

(tensor(0), tensor(90))

In [46]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [47]:
torch.sum(x)

tensor(450)

### Finding positional min and max
finding position of min or max in tensor

In [48]:
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* reshaping - reshape an input tensor to a defined shape
* view - return a view of an input tensor of a certain shape but keep same mem of original
* stacking - combine mutiple tensors on top of ech other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimension from a tensor
* unsqueeze - add a `1` dimension to a target tensor
* permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [50]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# change view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# stack on top
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# torch.squeze
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
x_reshaped.shape, x_reshaped.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [57]:
x_stacked.shape, x_stacked.squeeze().shape

(torch.Size([4, 9]), torch.Size([4, 9]))

In [58]:
# torch.unsqueeze()
x_stacked.shape, x_stacked.unsqueeze(dim=1).shape

(torch.Size([4, 9]), torch.Size([4, 1, 9]))

In [59]:
# torch.permute - rearrage the dim of matrix, uses original data
x_img = torch.rand(size=(224,224,3)) # height, width, RGB values

x_per = x_img.permute(2,0,1)

x_img.shape, x_per.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)
Indexing with pytorch is similar to numpy


In [60]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
x[0][0]

tensor([1, 2, 3])

In [63]:
x[0][0][0]

tensor(1)

In [64]:
# can use : to select all for target dim
x[:,0]

tensor([[1, 2, 3]])

In [65]:
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
x[:,1,1]

tensor([5])

In [67]:
x[0,0,:]

tensor([1, 2, 3])

## pytorch tensors and numpy
numpy is a popular scientific python numerical computing lib

pytorch has functionality to interactg with numpy
* data in numpy, want a pytorch tensor `torch.from_numpy(ndarray)`
* pytorch tensor to numpy `torch.Tensor.numpy()`

In [68]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
torch.arange(1.0, 8.0).dtype

torch.float32

np arange is float64

torch arange is float32

In [70]:
# tensor is a copy of np ndarray
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [72]:
# np ndarry is also a copy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (taking random out of random)
To reduce randomness in neural networks and pytroch comes with concept of a 
**Random seed**


In [73]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.8093, 0.2067, 0.3442, 0.7242],
         [0.5911, 0.2262, 0.4254, 0.6741],
         [0.5291, 0.9991, 0.2725, 0.3383]]),
 tensor([[0.1018, 0.5408, 0.7158, 0.0215],
         [0.2799, 0.0556, 0.7053, 0.8462],
         [0.9274, 0.1944, 0.1695, 0.1364]]))

In [74]:
# lets make a random reproducible tensors
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C, random_tensor_D



(tensor([[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]]))

## running tensor and pytorch object on the GPUS

GPUs = faster computation on numbers

### 1. getting a gpu

1. Easiest - Use google colab for a free gpu
2. Use your own
3. Use cloud computing - GCP, AWS, Azure

### 2. check for gpu access with pytorch

In [76]:
torch.cuda.is_available()


True

For pytorch since it's capable of running computer on the gpu or cpu, it best practice to setup device agnostic code

In [79]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [83]:
torch.cuda.get_device_capability()

(10, 3)

## 3. putting tensors and models on the gpu
The reason we want on gpu is it is faster

In [85]:
# create a tensor defaults on cpu
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [86]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###  4. Moving tensor back to the CPU 

In [91]:
# if tensor is on gpu, cant transform to numpy
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [90]:
# to fix gpu tensor, move back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu

<function Tensor.numpy>